### ISSUE TITLE
Map CalPhotos

### ISSUE THREAD

**Issue by mkoo** [BNHM/reservemapper#10]
What would be the best way to do this? If we premise the reservemapper that we are exploring datasets associated with reserves than again, we can allow searching on Calphotos as an option but would have to be separate from the current search boxes.
Open for discussion.

**Comment by jdeck88** [comment]
This would be easy to implement since photos in ecoengine already and can be called by API:

https://ecoengine.berkeley.edu/api/photos/?bbox=-124,44,-114,46&format=json

Suggestion is that we can use a Radio Button to choose either photos OR occurrences.  If choosing photos then we display just photos and have a different set of parameters we can pull from here:

https://ecoengine.berkeley.edu/docs/quickstart.html#search

**Comment by jdeck88** [comment]
This is implemented.
